# Generated by Django 4.1.1 on 2023-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=40)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('mob', models.IntegerField(default=123456, null=True)),
            ],
        ),
    ]
