# Generated by Django 4.1.1 on 2023-10-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emeter_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emeter',
            old_name='s',
            new_name='firstname',
        ),
    ]
