# Generated by Django 4.1.1 on 2023-10-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_s_emeter_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emeter',
            old_name='bs',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='emeter',
            name='t',
        ),
        migrations.RemoveField(
            model_name='emeter',
            name='tm',
        ),
        migrations.RemoveField(
            model_name='emeter',
            name='x',
        ),
    ]
