# Generated by Django 4.1.1 on 2023-10-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_bs_emeter_lastname_remove_emeter_t_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emeter',
            new_name='Person',
        ),
    ]
