# Generated by Django 4.1.1 on 2023-10-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_emeter_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subject',
            field=models.CharField(default=100, max_length=40),
        ),
    ]
