# Generated by Django 4.1.1 on 2023-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_subject_person_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='female',
            field=models.CharField(default=100, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='male',
            field=models.CharField(default=100, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='other',
            field=models.CharField(default=100, max_length=40),
        ),
    ]
