# Generated by Django 4.1.1 on 2023-10-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_person_female_person_male_person_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='female',
            field=models.CharField(default='female', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='male',
            field=models.CharField(default='male', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='other',
            field=models.CharField(default='other', max_length=40),
        ),
    ]
