# Generated by Django 4.1.1 on 2023-10-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_person_female_alter_person_male_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='female',
        ),
        migrations.AlterField(
            model_name='person',
            name='male',
            field=models.CharField(default='male', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='other',
            field=models.CharField(default='other', max_length=40, null=True),
        ),
    ]
