# Generated by Django 4.1.1 on 2023-10-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_person_female_alter_person_male_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='female',
            field=models.CharField(default='female', max_length=40, null=True),
        ),
    ]
