# Generated by Django 4.1.1 on 2023-10-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_person_female'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='female',
        ),
        migrations.RemoveField(
            model_name='person',
            name='male',
        ),
        migrations.RemoveField(
            model_name='person',
            name='other',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
