# Generated by Django 4.1.1 on 2023-10-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_person_female_remove_person_male_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='checks',
            new_name='subject',
        ),
    ]
