# Generated by Django 4.1.1 on 2023-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_person_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.CharField(default=100, max_length=40),
        ),
    ]
