# Generated by Django 4.1.1 on 2023-10-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
