# Generated by Django 4.1.1 on 2023-10-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_person_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
