# Generated by Django 4.1.1 on 2023-10-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_person_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='subject',
        ),
    ]
